server:
  port: 80
spring:
  application:
    name: cloud-eureka-client-consumer
  cloud:
    # consul 的相关配置
    consul:
      host: 192.168.31.66
      port: 8500
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${server.port}
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://peer1:7001/eureka/,http://peer2:7002/eureka/ # 服务的注册中心 高可用的模式
#    register-with-eureka: true
#    fetch-registry: true

