server:
  port: 7002 # 指定运行的端口
spring:
  application:
    name: cloud-eureka-server # 实例的名称
eureka:
  instance:
    hostname: peer2 # 实例的hostname
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/ # 服务地址
    fetch-registry: true # 是否拉取服务信息
    register-with-eureka: true # 是否注册自己
