server:
  port: 8004 # 端口号
spring:
  application:
    name: cloud-stream-source
  rabbitmq:
    host: 127.0.0.1 # 地址的配置
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders: # 在这里要绑定rabbit的基本的信息
        defaultRabbit: # 表示定义的名字 用于与binding进行整合
          type: rabbit
          environment:
            # 下面的配置与 直接配置是类似的
            spring:
              rabbitmq:
                host: 127.0.0.1 # 地址的配置
                port: 5672
                username: guest
                password: guest
      bindings:
        output:
          destination: studyExcehange # 表示用exchange的名称定义
          content-type: application/json
          binder: defaultRabbit # 设置绑定消息的具体的设置
# 服务注册中心的配置
eureka:
  client:
    service-url:
      defaultZone: http://peer1:7001/eureka/ # 服务的注册中心地址
    fetch-registry: true
    register-with-eureka: true